CREATE DATABASE IF NOT EXISTS `maximus`; USE `maximus`;
DROP TABLE IF EXISTS `student`;
DROP TABLE IF EXISTS `major`;
DROP TABLE IF EXISTS `faculty`;

CREATE TABLE IF NOT EXISTS `maximus`.`faculty` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NULL DEFAULT NULL,
	`description` VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `maximus`.`major` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NULL DEFAULT NULL,
	`description` VARCHAR(255) NULL DEFAULT NULL,
	`facultyID` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `maximus`.`student` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`studentID` VARCHAR(255) NULL DEFAULT NULL,
	`firstname` VARCHAR(255) NULL DEFAULT NULL,
	`lastname` VARCHAR(255) NULL DEFAULT NULL,
	`email` VARCHAR(255) NULL DEFAULT NULL,
	`phone` VARCHAR(255) NULL DEFAULT NULL,
	`majorID` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;